Stop merge if doesnt build
- Added code to stop merges if code doesnt build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,7 +4,7 @@ name: Deploy static content to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ['master']
+    branches: [ 'master' ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -38,7 +38,16 @@ jobs:
       - name: Install dependencies
         run: npm install
       - name: Build
-        run: npm run build
+        id: build
+        run: |
+          npm run build
+          build_exit_code=$?
+          if [ $build_exit_code -ne 0 ]; then
+          echo "Build failed with exit code $build_exit_code"
+          exit $build_exit_code
+          fi
+      - name: Check build status
+        run: exit ${{ steps.build.outcome }}
       - name: Setup Pages
         uses: actions/configure-pages@v3
       - name: Upload artifact
